include:
  - project: 'docker/process-webhooks'
    file: '/gitlab/deploy.yml'

variables:
  PROJECT_TO_BE_DEPLOYED: 'docker/sinonims'

stages:
  - build
#  - deploy

build:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker info
    - export DATETAG=$(date +%Y%m%d-%H%M%S)
  stage: build
  script:
    - docker build -f docker/Dockerfile --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:$DATETAG --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$DATETAG
    - docker push $CI_REGISTRY_IMAGE:latest

#deploy:
#  stage: deploy
#  extends:
#    .default-deploy
